### ISSUE TITLE
OpenVINO No module named 'cv2'

### ISSUE THREAD

**Issue by byarbrough** [byarbrough/movrasten#25]
This is the dreaded import cv2 error.
```
$make infer
sudo docker exec movrasten_app python infer/classification_sample.py -m /app/models/openvino/model.xml -nt 5 -i /app/data/infer/ -d CPU
Traceback (most recent call last):
  File "infer/classification_sample.py", line 23, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
Makefile:66: recipe for target 'infer' failed
make: *** [infer] Error 1
```
I've seen it before, as have many others, but going to try and fix it permanently this time.
ab92f8d

**Comment by byarbrough** [comment]
Multiple other issues address the same thing.
https://github.com/experiencor/keras-yolo2/issues/230
https://github.com/opencv/opencv/issues/7045
https://github.com/jazzsaxmafia/video_to_sequence/issues/3#issuecomment-277377381

After running `pip install opencv-python` as suggested, I was presented with a new error: 
```
$make infer
sudo docker exec movrasten_app python infer/classification_sample.py -m /app/models/openvino/model.xml -nt 5 -i /app/data/infer/ -d CPU
Traceback (most recent call last):
  File "infer/classification_sample.py", line 23, in <module>
    import cv2
  File "/usr/local/lib/python3.6/dist-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: libSM.so.6: cannot open shared object file: No such file or directory
Makefile:66: recipe for target 'infer' failed
make: *** [infer] Error 1
```

This led me to find more related issues:
https://github.com/ray-project/ray/issues/923
https://github.com/NVIDIA/nvidia-docker/issues/864#issuecomment-452023152

I added `apt-get install -y libsm6 libxext6 libxrender-dev` to Dockerfile, now the error is:
```
$ make infer
sudo docker exec movrasten_app python infer/classification_sample.py -m /app/models/openvino/model.xml -nt 5 -i /app/data/infer/ -d CPU
Traceback (most recent call last):
  File "infer/classification_sample.py", line 27, in <module>
    from openvino.inference_engine import IENetwork, IEPlugin
ModuleNotFoundError: No module named 'openvino'
Makefile:67: recipe for target 'infer' failed
make: *** [infer] Error 1
```
